export enum ServiceOrderDiagnosisOutcome {
  REPAIRABLE = 'REPAIRABLE',
  IRREPARABLE = 'IRREPARABLE',
  NOT_COST_EFFECTIVE = 'NOT_COST_EFFECTIVE',
  NO_PARTS_AVAILABLE = 'NO_PARTS_AVAILABLE',
  NO_FAULT_FOUND = 'NO_FAULT_FOUND',
  WARRANTY_APPLIES = 'WARRANTY_APPLIES',
  WARRANTY_REJECTED = 'WARRANTY_REJECTED',
}
