export enum WarrantyMovementType {
  ISSUED = 'ISSUED',
  RESERVED = 'RESERVED',
  RELEASED = 'RELEASED',
  CONSUMED = 'CONSUMED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
  TECHNICIAN_OVERRIDDEN = 'TECHNICIAN_OVERRIDDEN',
}
