export enum ServiceType {
  STANDARD_SERVICE = 'STANDARD_SERVICE',
  DIAGNOSIS = 'DIAGNOSIS',
  WARRANTY_SERVICE = 'WARRANTY_SERVICE',
  ASSEMBLY = 'ASSEMBLY',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
}
