export enum ServiceOrderOperativeStatus {
  ABIERTA = 'ABIERTA',
  EN_PROCESO = 'EN_PROCESO',
  LISTA_PARA_ENTREGA = 'LISTA_PARA_ENTREGA',
  ENTREGADA = 'ENTREGADA',
  CANCELADA = 'CANCELADA',
  CERRADA_SIN_SOLUCION = 'CERRADA_SIN_SOLUCION',
}
