export enum ServiceOrderCancellationStatus {
  PENDING = 'PENDING',
  AWAITING_CLIENT_ACCEPTANCE = 'AWAITING_CLIENT_ACCEPTANCE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ServiceOrderCancellationResolution {
  APPROVED_WITHOUT_CHARGE = 'APPROVED_WITHOUT_CHARGE',
  APPROVED_WITH_CHARGE = 'APPROVED_WITH_CHARGE',
  REJECTED = 'REJECTED',
}
