export enum ServiceOrderWorkflowStatus {
  ASSIGNED = 'ASSIGNED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DIAGNOSIS_READY = 'DIAGNOSIS_READY',
  UNDER_COORDINATION = 'UNDER_COORDINATION',
  APPROVED_FOR_WORK = 'APPROVED_FOR_WORK',
  IN_SERVICE = 'IN_SERVICE',
  WAITING_PARTS = 'WAITING_PARTS',
  SERVICE_DONE = 'SERVICE_DONE',
  NO_SOLUTION = 'NO_SOLUTION',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  CANCELLED = 'CANCELLED',
}
