export enum ServiceOrderStatus {
  OPEN = 'OPEN',
  ACTIVE = 'ACTIVE',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  CLOSED_NO_SOLUTION = 'CLOSED_NO_SOLUTION',
}
