export enum ServiceOrderCommercialStatus {
  NO_REQUIERE = 'NO_REQUIERE',
  PENDIENTE_PROPUESTA = 'PENDIENTE_PROPUESTA',
  PROPUESTA_EMITIDA = 'PROPUESTA_EMITIDA',
  PENDIENTE_RESPUESTA_CLIENTE = 'PENDIENTE_RESPUESTA_CLIENTE',
  AUTORIZADA = 'AUTORIZADA',
  RECHAZADA = 'RECHAZADA',
  EXPIRADA = 'EXPIRADA',
  REEMPLAZADA = 'REEMPLAZADA',
}
